"""adding at_closed to tasks

Revision ID: bcb9ad56c5b8
Revises: 4233ce4bfc66
Create Date: 2025-11-30 17:32:22.754300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb9ad56c5b8'
down_revision: Union[str, Sequence[str], None] = '4233ce4bfc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('at_closed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'at_closed')
    # ### end Alembic commands ###
